import Link from "next/link";
import type { Metadata } from "next";
import { Container, PageHeader } from "@/components/layout/PageShell";
import { Card, CardHeader } from "@/components/ui/primitives";
import { CATEGORIES } from "@/lib/data/categories";
import { ARCHIVE_DAYS } from "@/lib/data/results";
import { formatSchedule } from "@/lib/utils/format";
import { SITE, canonical } from "@/lib/site";

export const metadata: Metadata = {
  title: "About",
  description:
    "What Numera publishes, where the data comes from, how the archive is organised, and what this demonstration site is not.",
  alternates: { canonical: canonical("/about") },
  openGraph: {
    title: "About · Numera",
    description: "What this site publishes and how the demo data is generated.",
    url: canonical("/about"),
  },
};

export default function AboutPage() {
  return (
    <>
      <PageHeader
        title="About Numera"
        description={SITE.tagline}
        breadcrumbs={[{ href: "/", label: "Home" }, { label: "About" }]}
      />

      <Container className="py-8">
        <div className="grid gap-4 lg:grid-cols-3">
          <div className="space-y-4 lg:col-span-2">
            <Card className="p-5 sm:p-6">
              <h2 className="text-lg font-semibold tracking-tight">What this site is</h2>
              <div className="mt-3 space-y-3 text-sm text-muted">
                <p>
                  Numera is a results and statistics portal. It does one thing: publish a single
                  numerical value for each category at a fixed daily slot, keep every value in a
                  browsable archive, and describe that archive with plain statistics.
                </p>
                <p>
                  The board on the <Link href="/results" className="text-accent hover:underline">
                    current results
                  </Link>{" "}
                  page shows today. The{" "}
                  <Link href="/history" className="text-accent hover:underline">
                    archive
                  </Link>{" "}
                  holds {ARCHIVE_DAYS} days of history, filterable by category, date range and
                  status. The{" "}
                  <Link href="/statistics" className="text-accent hover:underline">
                    statistics
                  </Link>{" "}
                  page summarises what has already been published — volumes, timings and
                  distributions.
                </p>
              </div>
            </Card>

            <Card className="p-5 sm:p-6">
              <h2 className="text-lg font-semibold tracking-tight">What this site is not</h2>
              <div className="mt-3 space-y-3 text-sm text-muted">
                <p>
                  This is a demonstration build. It is not connected to any real service,
                  operator or organisation, and the categories are invented names.
                </p>
                <p>
                  There is no betting, wagering, deposit, withdrawal or payment functionality
                  here, and none is planned. Nothing on the site is a prediction, a tip, a
                  recommendation, or a claim about future values — the statistics pages
                  describe past data only.
                </p>
              </div>
            </Card>

            <Card className="p-5 sm:p-6">
              <h2 className="text-lg font-semibold tracking-tight">Where the data comes from</h2>
              <div className="mt-3 space-y-3 text-sm text-muted">
                <p>
                  Every value is generated by a seeded pseudo-random function keyed on the
                  category and the date. That makes the archive reproducible — the same date
                  always yields the same value — while today&apos;s board still fills in as each
                  scheduled slot passes.
                </p>
                <p>
                  The generator sits behind a service layer, and the pages and the public API
                  both read through that layer. Replacing the generator with a database means
                  changing one module.
                </p>
              </div>
            </Card>
          </div>

          <div className="space-y-4">
            <Card>
              <CardHeader title="Publication schedule" description="All times are local." />
              <ul className="divide-y divide-line text-sm">
                {CATEGORIES.map((category) => (
                  <li key={category.id} className="flex items-baseline justify-between gap-3 px-4 py-2.5">
                    <Link
                      href={`/categories/${category.slug}`}
                      className="truncate text-accent hover:underline"
                    >
                      {category.name}
                    </Link>
                    <span className="shrink-0 tabular text-muted">
                      {formatSchedule(category.scheduleTime)}
                    </span>
                  </li>
                ))}
              </ul>
            </Card>

            <Card>
              <CardHeader title="Status meanings" />
              <dl className="space-y-3 p-4 text-sm">
                <div>
                  <dt className="font-medium">Published</dt>
                  <dd className="text-muted">A value exists and has a publication timestamp.</dd>
                </div>
                <div>
                  <dt className="font-medium">Pending</dt>
                  <dd className="text-muted">
                    The scheduled slot has passed but no value has been published yet.
                  </dd>
                </div>
                <div>
                  <dt className="font-medium">Scheduled</dt>
                  <dd className="text-muted">The slot is still in the future.</dd>
                </div>
              </dl>
            </Card>

            <Card>
              <CardHeader title="Public API" description="Read-only JSON, same data as the site." />
              <ul className="space-y-1 p-4 font-mono text-xs text-muted">
                <li>GET /api/categories</li>
                <li>GET /api/categories/[slug]</li>
                <li>GET /api/results</li>
                <li>GET /api/results/[id]</li>
                <li>GET /api/history</li>
                <li>GET /api/statistics</li>
              </ul>
            </Card>
          </div>
        </div>
      </Container>
    </>
  );
}
