import Link from "next/link";
import type { Metadata } from "next";
import { AlertTriangle } from "lucide-react";
import { Container, PageHeader } from "@/components/layout/PageShell";
import { Card } from "@/components/ui/primitives";
import { canonical } from "@/lib/site";

export const metadata: Metadata = {
  title: "Disclaimer",
  description:
    "What Numera is, what it is not, and the limits of the data and statistics it publishes.",
  alternates: { canonical: canonical("/disclaimer") },
  openGraph: {
    title: "Disclaimer · Numera",
    description: "The limits of the data and statistics published here.",
    url: canonical("/disclaimer"),
  },
};

export default function DisclaimerPage() {
  return (
    <>
      <PageHeader
        title="Disclaimer"
        description="Please read this before drawing any conclusion from anything on this site."
        breadcrumbs={[{ href: "/", label: "Home" }, { label: "Disclaimer" }]}
      />

      <Container className="py-6 sm:py-8">
        <div className="mx-auto max-w-3xl space-y-3 sm:space-y-4">
          <Card className="flex gap-3 border-warn/40 bg-warn-soft p-4 sm:p-5">
            <AlertTriangle className="mt-0.5 size-5 shrink-0 text-warn" aria-hidden="true" />
            <p className="text-sm text-fg text-pretty">
              <strong>This is a demonstration site.</strong> Every market, schedule, timestamp and
              value shown here is fictional data generated by this application. None of it
              describes any real event, market, organisation or service.
            </p>
          </Card>

          <Card className="p-4 sm:p-6">
            <h2 className="text-lg font-semibold tracking-tight">No affiliation</h2>
            <p className="mt-3 text-sm text-muted text-pretty">
              Numera is not connected to, endorsed by, or operated on behalf of any real company,
              publisher or service. The market names are invented. Any resemblance to a real
              product or organisation is coincidental.
            </p>
          </Card>

          <Card className="p-4 sm:p-6">
            <h2 className="text-lg font-semibold tracking-tight">Statistics are descriptive only</h2>
            <div className="mt-3 space-y-3 text-sm text-muted text-pretty">
              <p>
                Every chart and summary on this site describes data that has already been
                published: how many entries exist, when they were published, and how often each
                value has appeared. That is the entire scope.
              </p>
              <p>
                Nothing here forecasts, predicts, or indicates what any market will publish next.
                Past frequency carries no information about future values — each value in this
                dataset is generated independently of the ones before it. Reading a trend into the{" "}
                <Link href="/charts" className="text-accent hover:underline">
                  frequency grid
                </Link>{" "}
                or the{" "}
                <Link href="/statistics" className="text-accent hover:underline">
                  distribution charts
                </Link>{" "}
                would be a mistake.
              </p>
            </div>
          </Card>

          <Card className="p-4 sm:p-6">
            <h2 className="text-lg font-semibold tracking-tight">What this site does not do</h2>
            <p className="mt-3 text-sm text-muted text-pretty">
              There is no betting, wagering, staking, deposit, withdrawal or payment functionality
              on this site, and none is planned. Nothing published here is a tip, a recommendation,
              a guaranteed outcome, or advice of any kind. No part of this site should be treated
              as an invitation to gamble.
            </p>
          </Card>

          <Card className="p-4 sm:p-6">
            <h2 className="text-lg font-semibold tracking-tight">Accuracy and availability</h2>
            <p className="mt-3 text-sm text-muted text-pretty">
              Because the data is generated rather than sourced, it is internally consistent but
              carries no external meaning. The site is provided as-is, with no warranty as to
              accuracy, completeness or availability.
            </p>
          </Card>

          <p className="text-sm text-muted text-pretty">
            More detail on how the data is produced is on the{" "}
            <Link href="/about" className="text-accent hover:underline">
              about page
            </Link>
            , and common questions are answered in the{" "}
            <Link href="/faqs" className="text-accent hover:underline">
              FAQs
            </Link>
            .
          </p>
        </div>
      </Container>
    </>
  );
}
